Repository MarvelProgramming/BetterTrader, pull requests merged in 2023-07, with the labels that each got.

#46 Fixed Various Bugs And Added Minor Updates
  BetterTraderClient/Assets/canvas.unity
  BetterTraderClient/MonoBehaviours/CustomDropdown.cs
  BetterTraderClient/MonoBehaviours/CustomScrollView.cs
  BetterTraderClient/MonoBehaviours/DraggableElement.cs
  BetterTraderClient/MonoBehaviours/ScalableElement.cs
  BetterTraderClient/MonoBehaviours/SortingManager.cs
  BetterTraderClient/MonoBehaviours/TradingMenu.cs
  BetterTraderClient/packages.lock.json
  BetterTraderLibrary/BTrader.cs
  BetterTraderServer/packages.lock.json
Labels: bug, enhancement

#48 Fixed Bugs And Included Minor Updates
  BetterTraderClient/Assets/canvas.unity
  BetterTraderClient/MonoBehaviours/CustomScrollView.cs
  BetterTraderClient/MonoBehaviours/ScalableElement.cs
Labels: bug, enhancement

#49 Setup Git For Unity
  UI/Assets/0Harmony.dll
  UI/Assets/AssetBundles/AssetBundles
  UI/Assets/AssetBundles/AssetBundles.manifest
  UI/Assets/AssetBundles/canvas.unity
  UI/Assets/AssetBundles/canvas.unity.manifest
  UI/Assets/BepInEx.dll
  UI/Assets/BetterTraderClient.dll
  UI/Assets/Jotunn.dll
  UI/Assets/Mono.Cecil.dll
  UI/Assets/Prefabs/BetterTraderClient_Canvas.prefab
  UI/Assets/Prefabs/DropdownOption.prefab
  UI/Assets/Prefabs/TradeItem.prefab
  UI/Assets/Presets/UIMutatorElementSelector.preset
  UI/Assets/Scenes/SampleScene.unity
  UI/Assets/Scripts/Editor/EnumEditor.cs
  UI/Assets/TextMesh Pro/Resources/Fonts & Materials/LiberationSans SDF - Fallback.asset
  UI/ProjectSettings/PackageManagerSettings.asset
Labels: enhancement

#53 Many Fixes, Added Features, And Refactorings
  BetterTraderClient/Assets/canvas.unity
  BetterTraderClient/BetterTraderClient.csproj
  BetterTraderClient/EventManager.cs
  BetterTraderClient/MonoBehaviours/CustomDropdown.cs
  BetterTraderClient/MonoBehaviours/CustomScrollView.cs
  BetterTraderClient/MonoBehaviours/DeselectEvent.cs
  BetterTraderClient/MonoBehaviours/DraggableElement.cs
  BetterTraderClient/MonoBehaviours/DropdownOption.cs
  BetterTraderClient/MonoBehaviours/ItemDetailsPopupPanel.cs
  BetterTraderClient/MonoBehaviours/ItemInspector.cs
  BetterTraderClient/MonoBehaviours/ItemPanel.cs
  BetterTraderClient/MonoBehaviours/NotificationPopupPanel.cs
  BetterTraderClient/MonoBehaviours/SortingManager.cs
  BetterTraderClient/MonoBehaviours/TradeMenuMock.cs
  BetterTraderClient/MonoBehaviours/TradingMenu.cs
  BetterTraderClient/Patches/StoreGui_Patches.cs
  BetterTraderClient/Patches/Terminal_Patches.cs
  BetterTraderClient/RPC.cs
  BetterTraderClient/Utils/StoreGui_Utils.cs
  BetterTraderLibrary/BTrader.cs
  BetterTraderLibrary/Extensions/GameObjectExtensions.cs
  BetterTraderLibrary/Extensions/ZNet_Extensions.cs
  BetterTraderLibrary/Interfaces/ITradable.cs
  BetterTraderLibrary/Item.cs
  BetterTraderLibrary/Utils/StoreGUIUtils.cs
  BetterTraderServer/BetterTraderServer.cs
  BetterTraderServer/BetterTraderServer.csproj
  BetterTraderServer/EventManager.cs
  BetterTraderServer/Patches/EnvMan_Patches.cs
  BetterTraderServer/Patches/ZNet_Patches.cs
  BetterTraderServer/RPC.cs
  Directory.Build.Props
  UI/Assets/AssetBundles/AssetBundles
  UI/Assets/AssetBundles/AssetBundles.manifest
  UI/Assets/AssetBundles/canvas.unity
  UI/Assets/AssetBundles/canvas.unity.manifest
  UI/Assets/BetterTraderClient.dll
  UI/Assets/Prefabs/BetterTraderClient_Canvas.prefab
  UI/Assets/Prefabs/DropdownOption.prefab
  UI/Assets/Prefabs/ItemDetailsPopupPanel.prefab
  UI/Assets/Prefabs/NotificationPopupPanel.prefab
  UI/Assets/Prefabs/TradeItem.prefab
  UI/Assets/Prefabs/TradeMenuActionButton.prefab
  UI/Assets/Prefabs/TraderMenuText_1.prefab
  UI/Assets/Prefabs/TraderMenuText_2.prefab
  UI/Assets/Prefabs/TraderMenuText_Base.prefab
  UI/Assets/Prefabs/TraderMenuText_Title.prefab
  UI/Assets/Prefabs/TraderModeButton.prefab
  UI/Assets/Presets/UIMutatorElementSelector.preset
  UI/Assets/Scenes/SampleScene.unity
  UI/Assets/Scripts/Editor/CreateAssetBundles.cs
  UI/Assets/TextMesh Pro/Resources/Fonts & Materials/LiberationSans SDF - Fallback.asset
  UI/Assets/TextMesh Pro/Resources/Fonts & Materials/LiberationSans SDF.asset
Labels: bug, enhancement

#58 Minor Fixes And Updates
  BetterTraderClient/Assets/canvas.unity
  BetterTraderClient/MonoBehaviours/CustomDropdown.cs
  BetterTraderClient/MonoBehaviours/CustomScrollView.cs
  BetterTraderClient/MonoBehaviours/ItemDetailsPopupPanel.cs
  BetterTraderClient/MonoBehaviours/ItemInspector.cs
  BetterTraderClient/MonoBehaviours/ItemPanel.cs
  BetterTraderClient/MonoBehaviours/TradingMenu.cs
  BetterTraderClient/Patches/InventoryGui_Patches.cs
  BetterTraderClient/Patches/Minimap_Patches.cs
  BetterTraderClient/Patches/StoreGui_Patches.cs
  BetterTraderLibrary/BTrader.cs
  BetterTraderLibrary/ConfigurationManager.cs
  BetterTraderLibrary/Extensions/GameObjectExtensions.cs
  BetterTraderLibrary/Extensions/ObjectDBExtensions.cs
  BetterTraderServer/BetterTraderServer.cs
  UI/Assets/0Harmony.dll
  UI/Assets/AssetBundles/AssetBundles
  UI/Assets/AssetBundles/AssetBundles.manifest
  UI/Assets/AssetBundles/canvas.unity
  UI/Assets/AssetBundles/canvas.unity.manifest
  UI/Assets/BetterTraderClient.dll
  UI/Assets/Mono.Cecil.dll
  UI/Assets/Prefabs/BetterTraderClient_Canvas.prefab
  UI/Assets/Prefabs/ItemInspectionPanel.prefab
  UI/Assets/Prefabs/TradeItem.prefab
  UI/Assets/Scenes/SampleScene.unity
  UI/Assets/TextMesh Pro/Resources/Fonts & Materials/LiberationSans SDF - Fallback.asset
  UI/Assets/TextMesh Pro/Resources/Fonts & Materials/LiberationSans SDF.asset
  UI/ProjectSettings/ProjectSettings.asset
Labels: bug, enhancement

#61 Minor Changes To Improve UX
  .gitignore
  BetterTrader/BetterTrader.csproj
  BetterTraderClient/Assets/canvas.unity
  BetterTraderClient/MonoBehaviours/CustomScrollView.cs
  BetterTraderClient/MonoBehaviours/ItemPanel.cs
  BetterTraderClient/MonoBehaviours/TradingMenu.cs
  BetterTraderClient/Patches/Terminal_Patches.cs
  BetterTraderClient/RPC.cs
  BetterTraderServer/RPC.cs
  UI/Assets/Animations/SelectedDecoration.controller
  UI/Assets/Animations/TradeItemSelectedDecoration_Activated.anim
  UI/Assets/AssetBundles/AssetBundles
  UI/Assets/AssetBundles/AssetBundles.manifest
  UI/Assets/AssetBundles/canvas.unity
  UI/Assets/AssetBundles/canvas.unity.manifest
  UI/Assets/BetterTrader.dll
  UI/Assets/Prefabs/BetterTraderClient_Canvas.prefab
  UI/Assets/Prefabs/TradeItem.prefab
  UI/Assets/Scenes/SampleScene.unity
Labels: bug, enhancement

#62 Fixed UI Compatibility Issue
  BetterTraderClient/Patches/StoreGui_Patches.cs
Labels: bug

#63 Gha automation
  .github/workflows/release-reuseable-workflow.yml
  .github/workflows/release.yml
  BetterTrader.sln
  BetterTrader/.ts/manifest.json
  BetterTrader/Directory.Build.props
  BetterTraderClient/BetterTraderClient.csproj
  BetterTraderServer/BetterTraderServer.csproj
Labels: enhancement

#66 Rename Directory.Build.Props to Directory.Build.props
  Directory.Build.props
Labels: bug

#67 Fixed Release Workflow XCopy Error
  BetterTrader/BetterTrader.csproj
Labels: bug

#68 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: enhancement
